SELECT NAME 
FROM v$database; -- 현제 DATABASE 명 검색 쿼리

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; -- 오라클 C## 사용자명 제거 쿼리

-- USER SQL
CREATE USER PROJECT_DATA IDENTIFIED BY "12345" -- 사용자 명 , 비밀번호
DEFAULT TABLESPACE "KIMKT_TABLESPACE"          -- 테이블 데이터 스페이스 명
TEMPORARY TABLESPACE "KIMKT_LOGSPACE"          -- 테이블 락 파일 명
ACCOUNT UNLOCK ;

GRANT CREATE SESSION TO PROJECT_DATA; -- 데이터 베이스 접속 권한

GRANT CREATE DATABASE LINK TO PROJECT_DATA; -- ???

GRANT CREATE TABLE TO PROJECT_DATA; -- 테이블 생성 권한

GRANT CREATE PROCEDURE TO PROJECT_DATA; -- 프로시져 권한

GRANT CONNECT , RESOURCE TO PROJECT_DATA; -- 관리자 권한

GRANT CREATE SYNONYM TO PROJECT_DATA; -- 테이블 검색 권한