/***********************************************************
 * USE        - SELECT , INSERT , UPDATE , DELETE , VO 쿼리
 * OUTPUT     - CONSOLE
 * VALUE      - SET_TABLE_NAME 테이블 명 변경
 ************************************************************/
DECLARE
	SET_TABLE_NAME VARCHAR2(50);
	LOOP_COUNT NUMBER;
 	QUERY TYPES.CURSORTYPE;
BEGIN
	SET_TABLE_NAME := 'USERS'; /* 해당 테이블명 작성 */
	LOOP_COUNT := 1;

	/* SELECT */
	DBMS_OUTPUT.PUT_LINE('/* SELECT */');
	FOR QUERY IN
				(SELECT ACC.COLUMN_NAME 
				   FROM ALL_COL_COMMENTS ACC
				  WHERE 1=1
				    AND ACC.TABLE_NAME = SET_TABLE_NAME)
	LOOP
		IF LOOP_COUNT = 1 THEN
	  		LOOP_COUNT := 2;
	    	DBMS_OUTPUT.PUT_LINE('SELECT ' || QUERY.COLUMN_NAME);
	  	ELSE
	    	DBMS_OUTPUT.PUT_LINE(',' || QUERY.COLUMN_NAME);
	  	END IF;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('FROM ' || SET_TABLE_NAME);
	
	/* INSERT */
	DBMS_OUTPUT.PUT_LINE('/* INSERT */');
	DBMS_OUTPUT.PUT_LINE('INSERT INTO ' || SET_TABLE_NAME || '(');
	FOR QUERY IN
				(SELECT ACC.COLUMN_NAME 
				   FROM ALL_COL_COMMENTS ACC
				  WHERE 1=1
				    AND ACC.TABLE_NAME = SET_TABLE_NAME)
	LOOP
		IF LOOP_COUNT = 2 THEN
	  		LOOP_COUNT := 3;
	    	DBMS_OUTPUT.PUT_LINE(QUERY.COLUMN_NAME);
	  	ELSE
	    	DBMS_OUTPUT.PUT_LINE(',' || QUERY.COLUMN_NAME);
	  	END IF;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('VALUES (');
	FOR QUERY IN
				(SELECT ACC.COLUMN_NAME 
				   FROM ALL_COL_COMMENTS ACC
				  WHERE 1=1
				    AND ACC.TABLE_NAME = SET_TABLE_NAME)
	LOOP
		IF LOOP_COUNT = 3 THEN
	  		LOOP_COUNT := 4;
	    	DBMS_OUTPUT.PUT_LINE('#{' || SUBSTR(LOWER(QUERY.COLUMN_NAME) , 1, 1) 
	                            || REPLACE(SUBSTR(INITCAP(QUERY.COLUMN_NAME) , 2), '_') || '}' );
	  	ELSE
	    	DBMS_OUTPUT.PUT_LINE(', #{' || SUBSTR(LOWER(QUERY.COLUMN_NAME) , 1, 1) 
	                            || REPLACE(SUBSTR(INITCAP(QUERY.COLUMN_NAME) , 2), '_') || '}' );
	  	END IF;	
	END LOOP;
	DBMS_OUTPUT.PUT_LINE(')');

	/* UPDATE */
	DBMS_OUTPUT.PUT_LINE('/* UPDATE */');
	FOR QUERY IN
				(SELECT ACC.COLUMN_NAME 
				   FROM ALL_COL_COMMENTS ACC
				  WHERE 1=1
				    AND ACC.TABLE_NAME = SET_TABLE_NAME)
	LOOP
		IF LOOP_COUNT = 4 THEN
	  		LOOP_COUNT := 5;
	    	DBMS_OUTPUT.PUT_LINE('UPDATE ' || SET_TABLE_NAME);
	    	DBMS_OUTPUT.PUT_LINE('SET ' || QUERY.COLUMN_NAME || ' = #{' || SUBSTR(LOWER(QUERY.COLUMN_NAME) , 1, 1) 
	                            || REPLACE(SUBSTR(INITCAP(QUERY.COLUMN_NAME) , 2), '_') || '}' );
	  	ELSE
	    	DBMS_OUTPUT.PUT_LINE(',' || QUERY.COLUMN_NAME || ' = #{' || SUBSTR(LOWER(QUERY.COLUMN_NAME) , 1, 1) 
	                            || REPLACE(SUBSTR(INITCAP(QUERY.COLUMN_NAME) , 2), '_') || '}' );
	  	END IF;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('WHERE 1=1 ');
	FOR QUERY IN 
				(SELECT COLUMN_NAME 
				   FROM USER_CONSTRAINTS UC INNER JOIN USER_CONS_COLUMNS UCC
					 ON (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
				  WHERE 1=1
					AND UC.TABLE_NAME = SET_TABLE_NAME
					AND UC.CONSTRAINT_TYPE = 'P')

	LOOP
		DBMS_OUTPUT.PUT_LINE('AND ' || QUERY.COLUMN_NAME || ' = #{' || INITCAP(QUERY.COLUMN_NAME) || '}' );
	END LOOP;

	/* DELETE */
	DBMS_OUTPUT.PUT_LINE('/* DELETE */');
	DBMS_OUTPUT.PUT_LINE('DELTE FROM ' || SET_TABLE_NAME);
	DBMS_OUTPUT.PUT_LINE('WHERE 1=1');
	FOR QUERY IN 
				(SELECT COLUMN_NAME 
				   FROM USER_CONSTRAINTS UC INNER JOIN USER_CONS_COLUMNS UCC
					 ON (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
				  WHERE 1=1
					AND UC.TABLE_NAME = SET_TABLE_NAME
					AND UC.CONSTRAINT_TYPE = 'P')

	LOOP
		DBMS_OUTPUT.PUT_LINE('AND ' || QUERY.COLUMN_NAME || ' =  #{' || SUBSTR(LOWER(QUERY.COLUMN_NAME) , 1, 1) 
	                        || REPLACE(SUBSTR(INITCAP(QUERY.COLUMN_NAME) , 2), '_') || '}'  );
	END LOOP;

	/* VO */
	DBMS_OUTPUT.PUT_LINE('/* VO */');
	FOR QUERY IN
				(SELECT ACC.COLUMN_NAME 
				      , ACC.COMMENTS
				   FROM ALL_COL_COMMENTS ACC
				  WHERE 1=1
				    AND ACC.TABLE_NAME = SET_TABLE_NAME)
	LOOP                    /* */
    	DBMS_OUTPUT.PUT_LINE('private String ' || QUERY.COLUMN_NAME || ' = ' || SUBSTR(LOWER(QUERY.COLUMN_NAME) , 1, 1) 
                            || REPLACE(SUBSTR(INITCAP(QUERY.COLUMN_NAME) , 2), '_') || '; // ' || QUERY.COMMENTS);
	END LOOP;
END;

/* VO 쿼리 추가 
 * DATA_TYPE를 변경 하고 싶을 때 가능
 * */
SELECT 'private '||
                   CASE 
                    WHEN ATC.DATA_TYPE = 'INT'
                     THEN 'Int'
                    WHEN ATC.DATA_TYPE = 'DATE'
                     THEN 'Date'
                    ELSE 'String'
                   END
                  || ' = ' || SUBSTR(LOWER(ACC.COLUMN_NAME) , 1, 1) 
                           || REPLACE(SUBSTR(INITCAP(ACC.COLUMN_NAME) , 2), '_') || '; // ' || ACC.COMMENTS
  FROM ALL_COL_COMMENTS ACC INNER JOIN ALL_TAB_COLUMNS ATC
    ON (ACC.COLUMN_NAME = ATC.COLUMN_NAME AND ACC.TABLE_NAME = ATC.TABLE_NAME)
 WHERE 1=1
   AND ACC.TABLE_NAME = 'USERS'; /* 테이블 명 */